import Head from 'next/head'
import Image from 'next/image'
import "@fontsource/work-sans"
import clouds from '../public/clouds.png'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1 className='header'>AI Avatar Generator</h1>
          <p className='paragraph'>Turn yourself into a greek philosopher</p>
        </div>
        <div>
          <h2 className='header'></h2>
        </div>
        <Image
      loader=""
      className='image'
      src={clouds}
      alt="Picture of the author"
      height={700}
        />
      </main>
    </>
  )
}
